// <auto-generated />
namespace Monera.Crawling.DGS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddSourceField : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddSourceField));
        
        string IMigrationMetadata.Id
        {
            get { return "201610041058104_AddSourceField"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
